development:
  dialect: mysql
  datasource: ${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_DATABASE}?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
  dir: internal/dataacess/database/migrations
